app:
  container_name: app
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - database:postgres
  environment:
    POSTGRES_USER: "app"
    POSTGRES_PASSWORD: "development-password"

database:
  container_name: database
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  volumes:
    - shuffled_data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: "app"
    POSTGRES_PASSWORD: "development-password"
